### ISSUE TITLE
Kent.Boogaart.Converters depend on Kent.Boogaart.HelperTrinity but you have unlisted it

### ISSUE THREAD

**Issue by AuroraDysis** [kentcb/WPFConverters#2]
you change it to HelperTrinity

**Comment by kentcb** [comment]
Can you explain why this is a problem? The dependency is still resolved - it doesn't have to be listed.

**Comment by AuroraDysis** [comment]
Sorry, I didn't see the readme in version 2.0.5. 1.5.2 is ok
